services:
  frontend:
    build: ./front-end-nextjs
    working_dir: /app
    command: sh -c "npm run build && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./front-end-nextjs:/app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FASTAPI_ENV=production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
