services:
  frontend:
    build: ./front-end-nextjs
    working_dir: /app
    command: sh -c "npm run build && npm start"
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - ./front-end-nextjs:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000" # Map host port 8000 to container port 80 (FastAPI)
    env_file:
      - ./backend/.env
    volumes:
      - ./api:/usr/src/app # Bind mount for live updates
    environment:
      - FASTAPI_ENV=production
