apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-backend
  template:
    metadata:
      labels:
        app: qr-backend
    spec:
      containers:
        - name: qr-backend
          image: surajkumar00/devops-url2qr-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mysecret

---
apiVersion: v1
kind: Service
metadata:
  name: qr-backend-service
spec:
  type: ClusterIP
  selector:
    app: qr-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
