apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-frontend
  template:
    metadata:
      labels:
        app: qr-frontend
    spec:
      containers:
        - name: qr-frontend
          image: surajkumar00/devops-url2qr-frontend:latest
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://qr-backend-service"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: qr-frontend-service
spec:
  type: ClusterIP
  selector:
    app: qr-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
