name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "front-end-nextjs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t surajkumar00/devops-url2qr-backend:latest ./backend
          docker push surajkumar00/devops-url2qr-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t surajkumar00/devops-url2qr-frontend:latest ./front-end-nextjs
          docker push surajkumar00/devops-url2qr-frontend:latest
